version: '3'

services:
  # app:
  #   build: .
  #   entrypoint: .docker/entrypoint.sh
  #   container_name: imdb-api
  #   ports:
  #     - '8080:8080'
  #   volumes:
  #     - .:/home/node/app
  #   depends_on:
  #     - db

  db:
    build: 
      context: .docker/postgres     
    container_name: imdb-db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
